[browser]
gatherUsageStats = false

[theme]
primaryColor = "#E694FF"
backgroundColor = "#00172B"
secondaryBackgroundColor = "#0083B8"
textColor = "#FFF"
font = "sans serif"

# Disable the hamburger menu
[menu]
items = []
